### PR TITLE
fix error when trying to read 0 bytes at eof

### PR DESCRIPTION
**Pull request by Skeeve**
Make sure you have checked _all_ steps below.

### Jira

I didn't know about Jira and have no clue what I have to do there

### Tests

No tests

### Commits

When reading an avro file record for record each time when reading the last record DataFileReader tries to get the next block but (of course) fails. This fixes the issue.

### CODE REVIEW

**Comment by RyanSkraba** [comment]
Hello @Skeeve !!  My apologies -- I don't follow PRs on this repo and didn't see your fix.  If you have a bug and a contribution, you should make it on the real https://github.com/apache/avro/ repositories for visibility!  That's where releases happen.

We'll probably ask you to create a JIRA with some simple code to reproduce the problem: https://issues.apache.org/jira/projects/AVRO

I can help out there if you like.  If you use Slack there's an Apache Software Foundation workspace at http://s.apache.org/slack-invite -- let's get this fixed for the next release!

**Comment by Skeeve** [comment]
Opened https://github.com/apache/avro/pull/1313

Cannot join the Slack Channel :(

**Comment by RyanSkraba** [comment]
Thanks so much and sorry for not checking here earlier!  It looks like you can't self-subscribe to slack any longer but if you're interested, I can send you an invitation by email.

In the meantime, I'll create a JIRA in your place to track this and we'll get some eyes on it to review.

**Comment by Skeeve** [comment]
Thanks Ryan. I just contacted you via Linkedin so that I can give you contact details.

**Pull request closed without merging**
